import Link from 'next/link';
import { Check, Minus, ShieldCheck } from 'lucide-react';

export const metadata = { title: 'Pricing | DevSync', description: 'Transparent DevSync plans and exact usage limits.' };

const plans = [
  { name: 'Free', price: '$0', cadence: 'forever', description: 'Evaluate the complete local scanning workflow.', cta: 'Start free', href: '/auth/signup', limits: ['3 projects', '5 team members', '100 scans / month', '0 managed preview hours'], features: ['CLI and VS Code scans', 'Schema drift reports', 'Application impact analysis', 'Safe change plans'] },
  { name: 'Team', price: '$49', cadence: 'per team / month', description: 'Shared controls for teams shipping database changes.', cta: 'Start with Team', href: '/auth/signup?plan=team', featured: true, limits: ['25 projects', '25 team members', '2,500 scans / month', '250 managed preview hours / month'], features: ['Everything in Free', 'Audit export', 'Managed previews', 'Approvals and promotions'] },
  { name: 'Enterprise', price: 'Custom', cadence: 'annual agreement', description: 'Identity, governance, and support for larger organizations.', cta: 'Contact us', href: 'mailto:devsync@bitlabsbuild.com?subject=DevSync%20Enterprise', limits: ['Unlimited projects', 'Unlimited team members', 'Unlimited scans', 'Unlimited managed preview hours'], features: ['Everything in Team', 'SSO and SCIM', 'Custom retention', 'Enterprise onboarding'] },
] as const;

export default function PricingPage() {
  return <main className="min-h-screen bg-background px-5 py-16 text-foreground"><div className="mx-auto max-w-6xl"><Link href="/" className="font-mono text-sm font-semibold text-primary">dev-sync</Link><div className="mt-14 max-w-2xl"><div className="font-mono text-xs uppercase tracking-[0.18em] text-primary">Simple, explicit limits</div><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Start safely. Pay when your team scales.</h1><p className="mt-4 text-muted-foreground">No credit card is required for Free. Limits reset monthly. A scan is one completed comparison of a repository schema and a database schema.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <section key={plan.name} className={`relative rounded-2xl border p-6 ${'featured' in plan ? 'border-primary bg-primary/5 shadow-lg shadow-primary/10' : 'bg-card'}`}>{'featured' in plan ? <span className="absolute right-5 top-5 rounded-full bg-primary px-2.5 py-1 text-[10px] font-semibold text-primary-foreground">Most popular</span> : null}<h2 className="text-xl font-semibold">{plan.name}</h2><div className="mt-5 text-4xl font-bold">{plan.price}</div><div className="mt-1 text-xs text-muted-foreground">{plan.cadence}</div><p className="mt-4 min-h-12 text-sm text-muted-foreground">{plan.description}</p><Link href={plan.href} className={`mt-6 flex h-10 items-center justify-center rounded-md text-sm font-medium ${'featured' in plan ? 'bg-primary text-primary-foreground' : 'border bg-background hover:bg-muted'}`}>{plan.cta}</Link><div className="mt-6 border-t pt-5"><h3 className="text-xs font-semibold uppercase tracking-wider">Exact limits</h3><ul className="mt-3 space-y-2">{plan.limits.map((item) => <li key={item} className="flex gap-2 text-sm"><Minus className="mt-0.5 h-4 w-4 text-primary" />{item}</li>)}</ul></div><div className="mt-6"><h3 className="text-xs font-semibold uppercase tracking-wider">Included</h3><ul className="mt-3 space-y-2">{plan.features.map((item) => <li key={item} className="flex gap-2 text-sm"><Check className="mt-0.5 h-4 w-4 text-emerald-500" />{item}</li>)}</ul></div></section>)}</div><div className="mt-8 flex gap-3 rounded-xl border bg-card p-4 text-sm text-muted-foreground"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-500" /><p>Database setup requires a verified read-only role. Generated plans do not execute SQL; execution is a separate, authenticated and confirmed action.</p></div></div></main>;
}
