import React, { useEffect, useMemo, useState } from 'react';
import type { CockpitSnapshot, CockpitView, HostToWebview, WebviewToHost } from '../../src/shared/protocol';
import { onHostMessage, send, vscode } from './bridge';
import { Button, DiffCard, EmptyState, LockEstimateCard, PipelineStepper, StatusPill } from './components';
import { DatabaseIcon, GitCompareIcon, HomeIcon, RocketIcon, SettingsIcon, ShieldIcon, SparklesIcon } from './icons';

const nav: Array<[CockpitView,React.ComponentType,string]> = [['overview',HomeIcon,'Overview'],['projects',GitCompareIcon,'Projects'],['project',ShieldIcon,'Project Control'],['scans',SparklesIcon,'Scans'],['environments',RocketIcon,'Environments'],['visualizer',DatabaseIcon,'Database Visualizer'],['teams',ShieldIcon,'Teams'],['analytics',GitCompareIcon,'Analytics'],['apiKeys',SettingsIcon,'API Keys'],['documentation',HomeIcon,'Documentation'],['settings',SettingsIcon,'Settings']];
const command = (name: Extract<WebviewToHost,{type:'command.run'}>['payload']['command']) => send({ type:'command.run', payload:{ command:name } });

export function App() {
  const [view,setView] = useState<CockpitView>((vscode.getState()?.view as CockpitView) || 'overview');
  const [snapshot,setSnapshot] = useState<CockpitSnapshot>();
  const [error,setError] = useState('');
  useEffect(() => onHostMessage((message: HostToWebview) => {
    if (message.type === 'host.ready' || message.type === 'state.update') setSnapshot(message.payload);
    if (message.type === 'navigation.open') navigate(message.payload.view);
    if (message.type === 'operation.error') setError(message.payload.message);
  }), []);
  useEffect(() => { send({type:'webview.ready'}); }, []);
  const navigate = (next:CockpitView) => { setView(next); vscode.setState({view:next}); send({type:'navigation.changed',payload:{view:next}}); };
  const body = useMemo(() => snapshot ? <View name={view} data={snapshot} navigate={navigate}/> : <div className="card">Loading DevSync state…</div>, [view,snapshot]);
  return <div className="app"><nav className="rail" aria-label="DevSync views">{nav.map(([id,NavIcon,label],i)=><button key={id} title={label} aria-label={label} className={`nav ${view===id?'active':''} ${i===nav.length-1?'bottom':''}`} onClick={()=>navigate(id)}><NavIcon/></button>)}</nav><main className="content">{error && <div className="notice row"><span>{error}</span><button className="nav" aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}{body}</main></div>;
}

function View({name,data,navigate}:{name:CockpitView;data:CockpitSnapshot;navigate(v:CockpitView):void}) {
  const report=data.state.scan.lastScanReport, mismatches=report?.mismatches ?? [];
  const dashboard=data.dashboard.data;
  if(name==='overview') return <><Header title="Overview" pill={data.session.status==='authenticated'?'Connected':'Signed out'}/><DashboardState data={data}/>{dashboard&&<><MetricGrid data={data}/><section className="card"><h2>Recent activity</h2><div className="stack">{dashboard.scans.slice(0,5).map(scan=><div className="row" key={scan.id}><span>{dashboard.projects.find(project=>project.id===scan.project_id)?.name||scan.project_id}</span><StatusPill tone={(scan.mismatches?.length||0)>0?'warn':'ok'}>{scan.status} · {scan.mismatches?.length||0} issues</StatusPill></div>)}</div></section></>}<section className="card"><h2>Quick actions</h2><div className="chips"><Button onClick={()=>send({type:'scan.run',payload:{}})}>Run scan</Button><Button secondary onClick={()=>command('devsync.createProject')}>Create project</Button><Button secondary onClick={()=>send({type:'dashboard.refresh'})}>Refresh</Button></div></section></>;
  if(name==='projects') return <><Header title="Projects" pill={`${dashboard?.projects.length||0} total`}/><DashboardState data={data}/><div className="stack">{dashboard?.projects.map(project=><section className="card" key={project.id}><div className="row"><div><h3>{project.name}</h3><span className="muted">{project.schema_type||'database'} · {project.id}</span></div><Button secondary onClick={()=>command('devsync.selectProject')}>Select</Button></div></section>)}{dashboard&&dashboard.projects.length===0&&<section className="card"><EmptyState icon="+" title="No projects" detail="Create a dashboard project without leaving VS Code." action="Create project" onAction={()=>command('devsync.createProject')}/></section>}</div></>;
  if(name==='project') return <ProjectControlPlane data={data}/>;
  if(name==='scans') return <><Header title="Scans" pill={`${dashboard?.scans.length||0} cloud scans`}/><DashboardState data={data}/>{data.state.scan.isScanning&&<div className="progress"/>}<section className="card"><div className="row"><h2>Scan controls</h2><div className="chips"><Button onClick={()=>send({type:'scan.run',payload:{}})}>Run scan</Button><Button secondary onClick={()=>send({type:'scan.run',payload:{local:true}})}>Local scan</Button></div></div></section>{mismatches.length>0?<div className="stack">{mismatches.map((m,i)=><section className={`card mismatch ${m.severity}`} key={`${m.type}-${m.model}-${i}`}><div className="row"><h3>{m.model}{'field'in m&&m.field?`.${m.field}`:''}</h3><StatusPill tone={m.severity==='error'?'bad':'warn'}>{m.severity}</StatusPill></div><DiffCard mismatch={m}/><LockEstimateCard severity={m.severity}/><div className="chips"><Button secondary onClick={()=>send({type:'fix.preview',payload:{mismatchIndex:i}})}>Preview</Button><Button onClick={()=>send({type:'fix.apply',payload:{mismatchIndex:i,confirm:true}})}>Apply fix</Button></div></section>)}</div>:<section className="card"><p className="muted">No local drift evidence is currently loaded.</p></section>}</>;
  if(name==='environments') return <><Header title="Environments" pill={`${dashboard?.environments.length||0} configured`}/><DashboardState data={data}/><section className="card stack"><h2>Promotion pipeline</h2><PipelineStepper/><div className="chips"><Button secondary onClick={()=>send({type:'promotion.action',payload:{action:'plan'}})}>Change plan</Button><Button secondary onClick={()=>send({type:'promotion.action',payload:{action:'policies'}})}>Policies</Button><Button onClick={()=>send({type:'promotion.action',payload:{action:'request'}})}>Request promotion</Button></div></section><div className="stack">{dashboard?.environments.map(environment=><section className="card row" key={environment.id}><div><h3>{environment.name}</h3><span className="muted">{environment.tier||environment.slug||'environment'}</span></div><StatusPill tone={environment.protected?'warn':'ok'}>{environment.requires_approval?'Approval required':'Automatic'}</StatusPill></section>)}</div></>;
  if(name==='teams') return <TeamView data={data}/>;
  if(name==='analytics') return <><Header title="Analytics" pill="Live records"/><DashboardState data={data}/><MetricGrid data={data}/></>;
  if(name==='apiKeys') return <><Header title="API Keys" pill="SecretStorage"/><section className="card"><h2>Extension authentication</h2><p className="muted">DevSync stores the device-flow access token in VS Code SecretStorage. Tokens are never rendered into the webview.</p><div className="row"><StatusPill tone={data.session.status==='authenticated'?'ok':'warn'}>{data.session.status}</StatusPill><Button onClick={()=>command(data.session.status==='authenticated'?'devsync.chat.logout':'devsync.chat.login')}>{data.session.status==='authenticated'?'Sign out':'Sign in'}</Button></div></section><section className="card"><h2>Active project ID</h2><code>{data.project?.id||'No project selected'}</code></section></>;
  if(name==='documentation') return <><Header title="Documentation" pill="DevSync"/><div className="grid"><section className="card"><h2>Schema workflow</h2><p className="muted">Scan, inspect evidence, preview fixes, then apply explicitly.</p></section><section className="card"><h2>Safety model</h2><p className="muted">Database inspection is read-only. Promotions require policy and approval gates.</p></section><Button onClick={()=>command('devsync.openDashboard')}>Open full documentation</Button></div></>;
  if(name==='home') return <><Header title="Home" pill={data.session.status==='authenticated'?'Connected':'Signed out'}/><div className="grid"><section className="card"><div className="row"><div><h2>{data.project?.name||data.workspace?.name||'No project selected'}</h2><span className="muted">{data.project?.id||'Connect a dashboard project to sync state'}</span></div><StatusPill tone={data.project?'ok':'warn'}>{data.project?'Configured':'Setup needed'}</StatusPill></div></section><section className="card"><h2>Schema health</h2>{report?<><div className="row"><strong>{mismatches.length?`${mismatches.length} mismatch${mismatches.length===1?'':'es'}`:'Schema synced'}</strong><StatusPill tone={mismatches.length?'warn':'ok'}>{report.status}</StatusPill></div><p className="muted">Last scan {new Date(report.completed_at||report.created_at).toLocaleString()}</p><Button onClick={()=>mismatches.length?navigate('drift'):send({type:'scan.run',payload:{}})}>{mismatches.length?'Review issues':'Scan again'}</Button></>:<EmptyState icon="⌁" title="No scan evidence yet" detail="Run a scan to compare code and database schemas." action={data.workspace?.configured?'Run first scan':'Start setup'} onAction={()=>data.workspace?.configured?send({type:'scan.run',payload:{}}):command('devsync.onboarding.start')}/>}</section><section className="card"><h2>Quick actions</h2><div className="chips"><Button secondary onClick={()=>send({type:'scan.run',payload:{local:true}})}>Local scan</Button><Button secondary onClick={()=>command('devsync.selectProject')}>Switch project</Button><Button secondary onClick={()=>command('devsync.openDashboard')}>Dashboard</Button></div></section></div></>;
  if(name==='visualizer') return <><Header title="Visualizer" pill="Live schema"/><section className="card"><EmptyState icon="◇" title="Schema graph focus mode" detail="Open the existing full graph renderer. Cockpit refresh and snapshot actions remain close at hand." action="Open ER diagram" onAction={()=>command('devsync.openERD')}/><div className="chips"><Button secondary onClick={()=>command('devsync.captureSchemaSnapshot')}>Capture snapshot</Button><Button secondary onClick={()=>send({type:'scan.run',payload:{local:true}})}>Refresh schema</Button></div></section></>;
  if(name==='drift') return <><Header title="Drift & Fixes" pill={`${mismatches.length} issues`}/>{data.state.scan.isScanning&&<div className="progress"/>}{!report?<section className="card"><EmptyState icon="≠" title="Nothing to review yet" detail="Scan the workspace to generate evidence-backed drift findings." action="Scan now" onAction={()=>send({type:'scan.run',payload:{}})}/></section>:mismatches.length===0?<section className="card"><EmptyState icon="✓" title="Schemas are in sync" detail="No differences were found in the latest scan." action="Scan again" onAction={()=>send({type:'scan.run',payload:{}})}/></section>:<div className="stack">{mismatches.map((m,i)=><section className={`card mismatch ${m.severity}`} key={`${m.type}-${m.model}-${i}`}><div className="row"><div><h3>{m.model}{'field'in m&&m.field?`.${m.field}`:''}</h3><span className="muted">{m.message||m.type.replace(/_/g,' ')}</span></div><StatusPill tone={m.severity==='error'?'bad':'warn'}>{m.severity}</StatusPill></div><DiffCard mismatch={m}/><LockEstimateCard severity={m.severity}/><div className="chips"><Button secondary onClick={()=>send({type:'fix.preview',payload:{mismatchIndex:i}})}>Preview</Button><Button onClick={()=>send({type:'fix.apply',payload:{mismatchIndex:i,confirm:true}})}>Apply fix</Button></div></section>)}</div>}</>;
  if(name==='migrations') return <><Header title="Migrations & Promotions" pill="Evidence gates"/><section className="card stack"><h2>Promotion pipeline</h2><PipelineStepper/><div className="chips"><Button secondary onClick={()=>send({type:'promotion.action',payload:{action:'plan'}})}>View plan</Button><Button secondary onClick={()=>send({type:'promotion.action',payload:{action:'policies'}})}>Policies</Button><Button onClick={()=>send({type:'promotion.action',payload:{action:'request'}})}>Request promotion</Button></div></section><section className="card"><div className="row"><h2>Migration history</h2><Button secondary onClick={()=>command('devsync.generateMigration')}>Generate</Button></div>{data.state.migration.migrations.length?<div className="stack">{data.state.migration.migrations.map(m=><div className="row" key={m.id}><span>{m.filename}</span><StatusPill tone={m.applied?'ok':''}>{m.applied?'Applied':'Pending'}</StatusPill></div>)}</div>:<p className="muted">No generated migrations in the current session.</p>}</section></>;
  if(name==='assistant') return <><Header title="Assistant" pill="Schema-aware"/><section className="card stack"><div className="chips"><span className="chip">@schema</span><span className="chip">@last-scan</span>{mismatches[0]&&<span className="chip">@table:{mismatches[0].model}</span>}</div><div className="empty"><div className="icon">✦</div><h3>Ask with evidence attached</h3><p className="muted">Open the existing streaming assistant with the current schema context.</p><Button onClick={()=>send({type:'chat.open'})}>Open assistant</Button></div><input className="input" disabled placeholder="Persistent inline conversation arrives through the chat service"/></section></>;
  if(name==='security') return <><Header title="Security & Audit" pill="Read only"/><div className="grid"><section className="card row"><div><h2>Database access</h2><span className="muted">Inspection mode prevents writes during scans.</span></div><StatusPill tone="ok">Read-only</StatusPill></section><section className="card row"><div><h2>Credential protection</h2><span className="muted">Connection strings are masked in UI and logs.</span></div><StatusPill tone="ok">Masked</StatusPill></section><section className="card"><h2>Recent audit activity</h2>{data.security.auditEntries.length?<div>{data.security.auditEntries.map(e=><div key={e.id}>{e.action}</div>)}</div>:<p className="muted">No security events recorded in this session.</p>}</section></div></>;
  return <><Header title="Settings" pill={data.queue.isPaused?'Queue paused':'Queue active'}/><div className="grid"><section className="card row"><div><h2>Workspace configuration</h2><span className="muted">Open .devsync/config.json or extension preferences.</span></div><div className="chips"><Button secondary onClick={()=>command('devsync.sidebar.openConfig')}>Config file</Button><Button onClick={()=>command('workbench.action.openSettings')}>Preferences</Button></div></section><section className="card row"><div><h2>Task queue</h2><span className="muted">{data.queue.queueLength} queued · {data.queue.runningTask||'idle'}</span></div><Button secondary onClick={()=>command(data.queue.isPaused?'devsync.queue.resume':'devsync.queue.pause')}>{data.queue.isPaused?'Resume':'Pause'}</Button></section><section className="card row"><div><h2>Account</h2><span className="muted">{data.session.status}</span></div><Button secondary onClick={()=>command(data.session.status==='authenticated'?'devsync.chat.logout':'devsync.chat.login')}>{data.session.status==='authenticated'?'Sign out':'Sign in'}</Button></section></div></>;
}
const Header=({title,pill}:{title:string;pill:string})=><header className="header"><h1>{title}</h1><StatusPill>{pill}</StatusPill></header>;

function DashboardState({data}:{data:CockpitSnapshot}) {
  if(data.session.status!=='authenticated') return <section className="card"><EmptyState icon="↗" title="Sign in required" detail="Connect your DevSync account to load the same cloud records as the dashboard." action="Sign in" onAction={()=>command('devsync.chat.login')}/></section>;
  if(data.dashboard.status==='loading'||data.dashboard.status==='idle') return <section className="card"><div className="progress"/><p className="muted">Loading dashboard records…</p></section>;
  if(data.dashboard.status==='error') return <section className="card"><h3>Dashboard data unavailable</h3><p className="muted">{data.dashboard.error}</p><Button onClick={()=>send({type:'dashboard.refresh'})}>Retry</Button></section>;
  return null;
}

function MetricGrid({data}:{data:CockpitSnapshot}) {
  const metrics=data.dashboard.data?.analytics;
  if(!metrics) return null;
  return <div className="pipeline"><section className="card"><span className="muted">Projects</span><h2>{metrics.projectCount}</h2></section><section className="card"><span className="muted">Scans</span><h2>{metrics.scanCount}</h2></section><section className="card"><span className="muted">Mismatches</span><h2>{metrics.mismatchTotal}</h2></section></div>;
}

function TeamView({data}:{data:CockpitSnapshot}) {
  const [name,setName]=useState('');
  const dashboard=data.dashboard.data;
  return <><Header title="Teams" pill={`${dashboard?.teams.length||0} memberships`}/><DashboardState data={data}/><section className="card stack"><h2>Create team</h2><input className="input" value={name} onChange={event=>setName(event.target.value)} placeholder="Engineering"/><Button onClick={()=>{if(name.trim())send({type:'dashboard.mutate',payload:{action:'team.create',values:{name:name.trim()}}});setName('');}}>Create team</Button></section><div className="stack">{dashboard?.teams.map(team=><section className="card row" key={team.id}><div><h3>{team.name}</h3><span className="muted">@{team.slug||team.id}</span></div><StatusPill>{team.role}</StatusPill></section>)}</div></>;
}

function ProjectControlPlane({data}:{data:CockpitSnapshot}) {
  const detail=data.dashboard.data?.projectDetail;
  if(!detail) return <><Header title="Project Control" pill="No active project"/><DashboardState data={data}/><section className="card"><EmptyState icon="◇" title="Select a project" detail="Choose an active project to load policies, promotions, migrations, approvals, GitHub, and collaboration records." action="Select project" onAction={()=>command('devsync.selectProject')}/></section></>;
  const project=detail.project as {name?:string;id?:string};
  const groups:Array<[string,Array<Record<string,unknown>>]>=[['Policies',detail.policies],['Promotions',detail.promotions],['Migrations',detail.migrations],['Rehearsals',detail.rehearsals],['Approvals',detail.approvals],['GitHub reviews',detail.githubReviews],['Comments',detail.comments],['Activity',detail.activity]];
  return <><Header title={project.name||'Project Control'} pill={project.id||'active'}/><section className="card"><div className="chips"><Button secondary onClick={()=>send({type:'promotion.action',payload:{action:'policies'}})}>Manage policies</Button><Button secondary onClick={()=>send({type:'promotion.action',payload:{action:'plan'}})}>Change plan</Button><Button onClick={()=>send({type:'promotion.action',payload:{action:'request'}})}>Promote</Button><Button secondary onClick={()=>command('devsync.generateMigration')}>Generate migration</Button></div></section><div className="grid">{groups.map(([label,items])=><section className="card" key={label}><div className="row"><h2>{label}</h2><StatusPill>{items.length}</StatusPill></div>{items.length===0?<p className="muted">No {label.toLowerCase()} recorded.</p>:<div className="stack">{items.slice(0,5).map((item,index)=><div className="row" key={String(item.id||index)}><span>{String(item.name||item.title||item.status||item.action||item.id||label)}</span>{item.status?<StatusPill>{String(item.status)}</StatusPill>:null}</div>)}</div>}</section>)}</div></>;
}
