import Link from 'next/link';
import { Database, Github, KeyRound, LockKeyhole, ShieldCheck, Trash2 } from 'lucide-react';

export const metadata = { title: 'Security & Data Handling | DevSync', description: 'How DevSync accesses, processes, stores, and removes customer data.' };
const controls = [
  { icon: Database, title: 'Database access', text: 'Guided setup accepts PostgreSQL connections only after verifying that the role has no table, schema, or database-create write privileges. Scans inspect schema metadata.' },
  { icon: Github, title: 'Repository access', text: 'The GitHub App requests read-only Contents permission. You select the installation and repositories. DevSync creates short-lived installation tokens when a scan needs access.' },
  { icon: KeyRound, title: 'Credentials', text: 'Database connection strings are encrypted with AES-256-GCM before storage. Browser responses expose only a masked preview. Production requires a deployment-specific encryption key.' },
  { icon: ShieldCheck, title: 'Change boundaries', text: 'Scanning and plan generation do not execute SQL. Approval freezes a plan version but does not execute it. Migration execution and rollback use separate authenticated endpoints and explicit confirmation.' },
  { icon: LockKeyhole, title: 'Tenant access', text: 'Row Level Security and server-side ownership or team-membership checks protect project, scan, plan, and team records.' },
  { icon: Trash2, title: 'Retention and deletion', text: 'Project records and reports remain while the project is active. Remove a project or request account deletion to remove application records, subject to limited security and legal retention.' },
];
export default function SecurityPage() {
  return <main className="min-h-screen bg-background px-5 py-16 text-foreground"><div className="mx-auto max-w-4xl"><Link href="/" className="font-mono text-sm font-semibold text-primary">dev-sync</Link><div className="mt-14 max-w-2xl"><div className="font-mono text-xs uppercase tracking-[0.18em] text-primary">Security & data handling</div><h1 className="mt-3 text-4xl font-bold tracking-tight">What DevSync can access—and what it cannot do.</h1><p className="mt-4 text-muted-foreground">This page describes implemented controls. DevSync does not currently claim SOC 2 certification or an external penetration-test attestation.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{controls.map(({ icon: Icon, title, text }) => <section key={title} className="rounded-2xl border bg-card p-5"><Icon className="h-5 w-5 text-primary" /><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></section>)}</div><section className="mt-8 rounded-2xl border bg-muted/20 p-6"><h2 className="font-semibold">AI data handling</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Deterministic scanning and plan generation do not require an AI provider. AI enrichment is optional; when invoked, relevant schema findings and plan context may be sent to the configured provider.</p></section><div className="mt-8 flex flex-wrap gap-4 text-sm"><Link href="/privacy" className="text-primary hover:underline">Privacy policy</Link><a href="mailto:devsync@bitlabsbuild.com?subject=DevSync%20security" className="text-primary hover:underline">Report a security concern</a></div></div></main>;
}
